routes/web.php
<?php

Route::get('/', 'SiteController@index')->name('site.index');
Route::get('groups', 'SiteController@groups')->name('site.groups');

Auth::routes();

Route::get('/home', 'DashboardController@today')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('profile', 'User\ProfileController@index')->name('profile');
    Route::post('profile', 'User\ProfileController@update')->name('profile.update');
    Route::post('profile/pass', 'User\ProfileController@updatePassword')->name('profile.update.password');

    Route::get('game/today', 'DashboardController@today')->name('game.today');
    Route::get('game/tomorrow', 'DashboardController@tomorrow')->name('game.tomorrow');
    Route::get('game/past', 'DashboardController@past')->name('game.past');

});

Route::middleware('auth', 'is_admin')->group(function () {
    Route::resource('user', 'UserController', ['only' => ['index', 'update']]);
    Route::resource('game', 'GameController');
    Route::resource('group', 'GroupController');
});

resources/views/pieces/errors.blade.php
<?php /**@var Illuminate\Support\ViewErrorBag $errors  */ ?>
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/pieces/menu.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">اصلی</li>
                <li class="has_sub">
                    <a href="{{ route('home') }}" class="waves-effect"><i class="ti-home"></i> <span> داشبورد </span> </a>
                </li>
                <li  class="has_sub">
                    <a href="{{ route('game.today') }}" class="waves-effect"><i class="ti-cloud-down"></i> <span> بازی های امروز</span> </a>
                    <a href="{{ route('game.tomorrow') }}" class="waves-effect"><i class="ti-cloud-up"></i> <span> بازی های فردا</span> </a>
                    <a href="{{ route('game.past') }}" class="waves-effect"><i class="ti-cloud-up"></i> <span> بازی های قبل</span> </a>
                </li>
                @if(auth()->user()->is_admin)
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect">
                        <i class="ti-paint-bucket"></i>
                        <span> مدیریت بازی ها  </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('group.index') }}">گروه های پیش بینی</a></li>
                        <li><a href="{{ route('game.create') }}">افزودن بازی</a></li>
                        <li><a href="{{ route('game.index') }}">نمایش کل بازی ها</a></li>
                    </ul>
                </li>
                <li >
                    <a href="{{ route('user.index') }}" class="waves-effect"><i class="ti-user"></i> <span> کاربران</span> </a>
                </li>
                @endif
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>