routes/web.php
<?php

Route::get('/', 'SiteController@index')->name('site.index');
Route::get('groups', 'SiteController@groups')->name('site.groups');

Auth::routes();

Route::get('/home', 'DashboardController@today')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('profile', 'User\ProfileController@index')->name('profile');
    Route::post('profile', 'User\ProfileController@update')->name('profile.update');
    Route::post('profile/pass', 'User\ProfileController@updatePassword')->name('profile.update.password');

    Route::get('game/today', 'DashboardController@today')->name('game.today');
    Route::get('game/tomorrow', 'DashboardController@tomorrow')->name('game.tomorrow');
    Route::get('game/past', 'DashboardController@past')->name('game.past');

});

Route::middleware('auth', 'is_admin')->group(function () {
    Route::resource('user', 'UserController', ['only' => ['index', 'update']]);
    Route::resource('game', 'GameController');
    Route::resource('group', 'GroupController');
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Group
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Game[] $game
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Group whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Group extends Model
{
    const _TABLE = 'groups';
    const ID = 'id';
    const NAME = 'name';
    const SLUG = 'slug';

    protected $table = self::_TABLE;
    protected $guarded = [];

    /**
     * retrieve game
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function game()
    {
        return $this->hasMany(
            Game::class,
        Game::GROUP_ID,
          self::ID
        );
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Http\Requests\GroupRequest;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = Group::orderBy(Group::ID, 'desc')->get();

        return view('group.index', compact('groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\GroupRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(GroupRequest $request)
    {
        $group = new Group();
        $group->name = $request->get(GroupRequest::NAME);
        $group->slug = $request->get(GroupRequest::SLUG);
        $group->save();

        return response()->json(
            [
                'message' => 'Group created.',
                'error' => false
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $group->name = $request->get(GroupRequest::NAME);
        $group->slug = $request->get(GroupRequest::SLUG);
        $group->save();

        return response()->json(
            [
                'message' => 'Group updated.',
                'error' => false
            ]
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Group $group
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Group $group)
    {
        $group->delete();

        return response()->json(
            [
                'message' => 'Group deleted.',
                'error' => false
            ]
        );
    }
}

resources/views/group/index.blade.php
@extends('layouts.app')
<?php /** @var \App\User $users */ ?>
@section('css')
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <h3>گروه های پیش بینی</h3>
                <div id="jsGrid"></div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
    <script type="text/javascript">
        var clients = {!! $groups !!};
    </script>
    <script>
        $("#jsGrid").jsGrid({
            width: "100%",
            filtering:true,
            inserting: true,
            editing: true,
            sorting: true,
            paging: true,

            data: clients,
            onItemInserting: function(args) {
                var url = '{{ route('group.store') }}';
                $.post(
                    url,
                    {
                        name:args.item.name,
                        slug:args.item.slug,
                    },
                    function (res) {
                        $.Notification.notify('custom','top left', '{{ __('k.message') }}', res.message)
                    }
                );
            },
            onItemUpdated: function(args) {
                var url = '{{ route('group.index') }}/' + args.item.id;
                $.post(
                    url,
                    {
                        _method:'PATCH',
                        name:args.item.name,
                        slug:args.item.slug,
                    },
                    function (res) {
                        $.Notification.notify('custom','top left', '{{ __('k.message') }}', res.message)
                    }
                );
            },
            onItemDeleted: function(args) {
                var url = '{{ route('group.index') }}/' + args.item.id;
                $.post(
                    url,
                    {
                        _method:'DELETE',
                    },
                    function (res) {
                        $.Notification.notify('custom','top left', '{{ __('k.message') }}', res.message)
                    }
                );
            },
            fields: [
                { name: "name", type: "text", validate: "required" },
                { name: "slug", type: "text", validate: "required" },
                { type: "control" }
            ]
        });
    </script>
@endsection