routes/web.php
<?php

Route::get('/', 'SiteController@index')->name('site.index');
Route::get('groups', 'SiteController@groups')->name('site.groups');

Auth::routes();

Route::get('/home', 'DashboardController@today')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('profile', 'User\ProfileController@index')->name('profile');
    Route::post('profile', 'User\ProfileController@update')->name('profile.update');
    Route::post('profile/pass', 'User\ProfileController@updatePassword')->name('profile.update.password');

    Route::get('game/today', 'DashboardController@today')->name('game.today');
    Route::get('game/tomorrow', 'DashboardController@tomorrow')->name('game.tomorrow');
    Route::get('game/past', 'DashboardController@past')->name('game.past');

});

Route::middleware('auth', 'is_admin')->group(function () {
    Route::resource('user', 'UserController', ['only' => ['index', 'update']]);
    Route::resource('game', 'GameController');
    Route::resource('group', 'GroupController');
});

app/Game.php
<?php

namespace App;

use App\ModelScopes\GameScope;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Game
 *
 * @property int $id
 * @property mixed $data
 * @property \Illuminate\Support\Carbon $holding_time
 * @property int|null $result
 * @property int $status
 * @property int $type
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game canceled()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game deferment()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game draw()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game guestWinner()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game hostWinner()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereData($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereHoldingTime($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereResult($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereStatus($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereUpdatedAt($value)
 * @mixin \Eloquent
 * @mixin \Illuminate\Database\Eloquent\Builder
 * @property int $league_id
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereLeagueId($value)
 * @property string $host_name
 * @property string $guest_name
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereGuestName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereHostName($value)
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\GamePrediction[] $predictions
 * @property string $league
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereLeague($value)
 * @property string $prediction
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game wherePrediction($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game free()
 * @property string $group_id
 * @property-read \App\Group $group
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Game whereGroupId($value)
 */
class Game extends Model
{
    const _TABLE = 'games';

    const ID = 'id';
    const GROUP_ID = 'group_id';
    const LEAGUE = 'league';
    const HOST_NAME = 'host_name';
    const GUEST_NAME = 'guest_name';
    const HOLDING_TIME = 'holding_time';
    const PREDICTION = 'prediction';
    const RESULT = 'result';
    const STATUS = 'status';
    const TYPE = 'type';
    const TYPE_FREE = '0';
    const TYPE_VIP = '1';

    protected $table = self::_TABLE;
    protected $guarded = [];
    protected $dates = [self::HOLDING_TIME];


    /**
     * retrieve group
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function group()
    {
        return $this->belongsTo(
            Group::class,
            self::GROUP_ID,
            Group::ID
        );
    }

    /**
     * get today game
     *
     * @param $query
     *
     * @return mixed
     */
    public function ScopeTodayGame($query)
    {
        return $query->where(self::HOLDING_TIME, '>=', Carbon::today())
            ->where(self::HOLDING_TIME, '<', Carbon::tomorrow());
    }

    /**
     * get tomorrow game
     *
     * @param $query
     *
     * @return mixed
     */
    public function ScopeTomorrowGame($query)
    {
        return $query->where(self::HOLDING_TIME, '>=', Carbon::tomorrow())
            ->where(self::HOLDING_TIME, '<', Carbon::tomorrow()->addDay(1));
    }

    /**
     * get past game
     *
     * @param $query
     *
     * @return mixed
     */
    public function ScopePastGame($query)
    {
        return $query->where(self::HOLDING_TIME, '<', Carbon::today());
    }

    /**
     * get free game
     *
     * @param $query
     *
     * @return mixed
     */
    public function scopeFree($query)
    {
        return $query->where(self::TYPE, self::TYPE_FREE);
    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Game;
use App\Group;
use App\Http\Requests\Game\GameRequest;
use Carbon\Carbon;
use Illuminate\Http\Request;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $games = Game::orderBy(Game::HOLDING_TIME, 'desc')->paginate(25);
        $groups = Group::all();

        return view('game.index', compact('games', 'groups'));
    }

    /**
     * Show the resource.
     *
     * @param \App\Game $game
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Game $game)
    {
        return view('game.show', compact('game'));
    }

    /**
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $games = Game::orderBy(Game::ID, 'desc')->take(100)->paginate(25);
        $groups = Group::all();

        return view('game.create', compact('games', 'groups'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\Game\GameRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(GameRequest $request)
    {
        $game = new Game();
        $this->setGameValues($request, $game);
        $game->save();

        return back()->with('message', 'game created successfully');
    }

    /**
     * Display the specified resource to edit.
     *
     * @param \App\Game $game
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit(Game $game)
    {
        $data = $game->toArray();
        $data[Game::HOLDING_TIME] = $game->holding_time->format('H:i');
        $data['holding_date'] = $game->holding_time->format('Y-m-d');
        $data['find'] = true;

       return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\Game\GameRequest $request
     * @param \App\Game                           $game
     *
     * @return \Illuminate\Http\Response
     */
    public function update(GameRequest $request, Game $game)
    {
        $this->setGameValues($request, $game);
        $game->save();

        if ($request->isXmlHttpRequest()) {
            return response()->json(['message' => 'updated', 'finish' => true]);
        } else {
            return back()->with('message', 'updated');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Game $game
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Game $game)
    {
       $game->delete();

       return response()->json(['message' => 'game Deleted']);
    }

    /**
     * set game values from request
     *
     * @param \App\Http\Requests\Game\GameRequest $request
     * @param                                     $game
     */
    private function setGameValues(GameRequest $request, $game): void
    {
        $game->group_id = $request->get(GameRequest::GROUP);
        $game->league = $request->get(GameRequest::LEAGUE);
        $game->host_name = $request->get(GameRequest::HOST);
        $game->guest_name = $request->get(GameRequest::GUEST);
        $game->prediction = $request->get(GameRequest::PREDICTION);
        $game->holding_time = Carbon::parse(
            $request->get(GameRequest::HOLDING_DATE) . ' ' . $request->get(GameRequest::HOLDING_TIME)
        )->format('Y-m-d H:i:s');
    }
}

resources/views/game/create.blade.php
@extends('layouts.app')
@section('css')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css"
          rel="stylesheet"/>
@endsection
@section('content')

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="m-t-0 header-title"><b>افزودن بازی</b></h4>
                <p class="p-b-10"></p>
                <form action="{{ route('game.store') }}" class="form" method="post">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-md-2 control-label">لیگ</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="league">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">میزبان</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="host">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">میهمان</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="guest">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">پیش بینی</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="prediction">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="col-md-2 control-label">تاریخ</label>
                                <div class="col-md-10">
                                    <input type="date" class="form-control" name="holding_date">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label"> ساعت</label>
                                <div class="col-md-10">
                                    <input type="text" id="g-holding-edit-time" class="form-control timepicker"
                                           name="holding_time">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">نوع</label>
                                <div class="col-md-10">
                                    <select type="text" class="form-control" name="type">
                                        <option value="0">{{ __('gameType.0') }}</option>
                                        <option value="1">{{ __('gameType.1') }}</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label">گروه</label>
                                <div class="col-md-10">
                                    <select type="text" class="form-control" name="group">
                                    @foreach($groups as $group)
                                        <option value="{{ $group->id }}">{{ $group->name }}</option>
                                    @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <button class="btn btn-sm btn-primary" type="submit">
                        <i class="fa fa-check"></i> {{__('k.save')}}
                    </button>
                    <button class="btn btn-sm btn-inverse" type="reset">
                        <i class="fa fa-refresh"></i> {{__('k.reset')}}
                    </button>
                </form>
            </div>
        </div>
    </div>
    {{--table--}}
    @include('game.game_table', $games)

    {{--modal--}}
    @include('game.edit_modal')

@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $('.timepicker').datetimepicker({
                format: 'HH:mm'
            });
        });
    </script>
@endsection

resources/views/game/edit_modal.blade.php
<div id="game-edit-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="pg-add-title"></h4>
            </div>
            <div class="modal-body">
                <form class="form form-inline" action="" id="game-form-edit" method="post">
                    <input type="hidden" value="PUT" name="_method">
                    @csrf
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-danger waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false">میزبان</button>
                            </div>
                            <input name="host" type="text" id="g-host-edit" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-danger waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false">لیگ</button>
                            </div>
                            <input name="league" type="text" id="g-league-edit" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-danger waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false">گروه</button>
                            </div>
                            <select name="group" type="text" id="g-group-edit" class="form-control" >
                                @foreach($groups as $group)
                                    <option value="{{ $group->id }}"> {{ $group->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-primary waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false">میهمان</button>
                            </div>
                            <input name="guest" type="text" id="g-guest-edit" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false"> روز مسابقه</button>
                            </div>
                            <input type="date"  id="m-holding-edit-date" class="form-control" name="holding_date">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group" id='datetimepicker3'>
                            <div class="input-group-btn">
                                <button type="button" class="btn waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false"> ساعت مسابقه</button>
                            </div>
                            <input type="text" id="m-holding-edit-time" class="form-control timepickers" name="holding_time">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" class="btn waves-effect waves-light btn-facebook dropdown-toggle"  aria-expanded="false"> پییش بینی</button>
                            </div>
                            <input type="text" id="g-prediction-edit" class="form-control " name="prediction">
                        </div>
                    </div>

                    <hr>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-success"><i class="fa fa-check"></i> {{__('k.save')}}</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('.timepickers').datetimepicker({
            format: 'HH:mm'
        });
    });
    $('button#edit').click(function (e) {
        var _id = $(this).attr('data-id');
        $.get(
            '{{ route('game.index') }}/' + _id + '/edit',
            {},
            function(res){
                if (res.find == true) {
                    showEditModal(res)
                }
            }
        );
    });

    function showEditModal(game) {
        $('#g-group-edit').val(game.group_id);
        $('#g-guest-edit').val(game.guest_name);
        $('#g-host-edit').val(game.host_name);
        $('#g-league-edit').val(game.league);
        $('#g-prediction-edit').val(game.prediction);
        $('#m-holding-edit-time').val(game.holding_time);
        $('#m-holding-edit-date').val(game.holding_date);
        $('#game-form-edit').attr('action', '{{ route('game.index') }}/' + game.id);
        $('#game-edit-modal').modal();
    }

</script>

resources/views/game/game_table.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="">
            <div class="card-box">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <h4 class="m-t-0 header-title"><b>مسابقات</b></h4>
                        <p class="text-muted font-13 m-b-30"></p>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ __('k.league') }}</th>
                                <th>{{ __('k.host') }}</th>
                                <th>{{ __('k.guest') }}</th>
                                <th>{{ __('k.holding_time') }}</th>
                                <th>{{ __('k.prediction') }}</th>
                                <th>{{ __('k.result') }}</th>
                                <th>{{ __('k.type') }}</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php /** @var \Illuminate\Support\Collection $games  */ ?>
                            <?php /** @var \App\Game $game  */ ?>
                            @foreach($games as $key => $game)
                            <tr>
                                <td> {{ ++$key }}</td>
                                <td>{{ $game->league }}</td>
                                <td>{{ $game->host_name }}</td>
                                <td>{{ $game->guest_name }}</td>
                                <td>{{ $game->holding_time }}</td>
                                <td>{{ $game->prediction }}</td>
                                <td>{{ $game->result }}</td>
                                <td>{{ __('gameType.' . $game->type) }}</td>
                                <td>
                                    <button class="btn btn-sm btn-primary" id="edit" data-id="{{$game->id}}">ویرایش <i class="fa fa-edit"></i> </button>
                                    <button class="btn btn-sm btn-danger" id="delete"
                                            onclick="deleteRecord(
                                                   $(this).parent().parent(),
                                                       '{{ route('game.destroy', $game->id) }}'
                                                       )">حذف  <i class="fa fa-remove"> </i>
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $games->render() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/game/index.blade.php
@extends('layouts.app')

@section('content')
   @include('game.game_table', $games)
    {{--modal--}}
    @include('game.edit_modal')
@endsection

resources/views/game/show.blade.php
@extends('layouts.app')

@section('css')
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid-theme.min.css" />
@endsection
@section('content')
    <?php /** @var \App\Game $game */ ?>
    <div class="row">
        <div class="col-md-12">
            <div class="">
                <div class="card-box">
                    <div class="row">
                      <div class="col-lg-8 col-lg-offset-2">
                          <h3 style="text-align: center"> host : <span style="color: #628cff"> {{ $game->host_name }}</span>
                              - guest :  <span style="color: #ff4a7b">  {{ $game->guest_name }}</span>
                          </h3>
                          <p style="text-align: center"> holding time : {{ $game->holding_time }}</p>
                          <p style="text-align: center"> لیگ : {{ $game->league }}</p>
                      </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div id="jsGrid"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsgrid/1.5.3/jsgrid.min.js"></script>
    <script type="text/javascript">
        var data = {!! $game->predictions->toJson() !!};
    </script>

    <script type="text/javascript">
        var items = [
            { Name: "نامشخص", Id: 0 },
            { Name: "درست", Id: 1 },
            { Name: "غلط", Id: 2 },
        ];

        $("#jsGrid").jsGrid({
            width: "100%",
            height: "400px",

            inserting: true,
            editing: true,
            sorting: true,
            paging: true,

            data: data,

            onItemInserting: function(args) {
                $.post(
                    '{{ route('prediction.store', $game->id) }}',
                    {
                        prediction: args.item.prediction,
                        description: args.item.description,
                        status: args.item.status
                    },
                    function(res) {

                    }
                );
            },
            onItemUpdating: function(args) {
                $.post(
                    '{{ route('prediction.store', $game->id) }}/' + args.item.id,
                    {
                        _method: 'put',
                        prediction: args.item.prediction,
                        description: args.item.description,
                        status: args.item.status
                    },
                    function(res) {

                    }
                );
            },
            onItemDeleting: function(args) {
                $.post(
                    '{{ route('prediction.store', $game->id) }}/' + args.item.id ,
                    {
                      _method:'delete'
                    },
                    function(res) {
                        console.log(res);
                    }
                );
            },
            fields: [
                { name: "prediction", title: 'پیش بینی', type: "text", width: 150, validate: "required" },
                { name: "description", title: 'توضیحات', type: "text", width: 200 },
                { name: "status", title: 'وضعیت', type: "select", items: items, valueField: "Id", textField: "Name" ,validate: "required"},
                { type: "control" }
            ]
        });
    </script>
@endsection

resources/views/game/table.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="{{ url('') }}/assets/plugins/datatable/jquery.dataTables.css" />
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="">
                <div class="card-box">
                    <div class="row">
                        <h3><i class="fa fa-list"></i> لیست پیش بینی ها</h3>
                        <hr>
                        <table id="datatable" class="table table-striped">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td>{{ __('k.league') }}</td>
                                <td>{{ __('k.match') }}</td>
                                <td>{{ __('k.holding_time') }}</td>
                                <td>{{ __('k.prediction') }}</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $key => $game)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $game['league'] }}</td>
                                <td>{{ $game['host'] }}
                                    <strong style="color: #b91d19;">VS</strong>
                                    {{ $game['guest'] }}</td>
                                <td>{{ $game['holding_time'] }}</td>
                                <td>{{ $game['prediction'] }}</td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script type="text/javascript" src="{{ url('') }}/assets/plugins/datatable/jquery.dataTables.js"></script>
    <script type="text/javascript">
        $('#datatable').dataTable({
            "pageLength": 20
        });
    </script>
@endsection